extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_lights;
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_Plane_002_mesh_layer_1[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
